[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    connectSrc = "'self' https://www.google-analytics.com"
    imgSrc = "'self' data: https://assets.forestry.io"
    scriptSrc = "'self' https://www.google-analytics.com https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com"
    styleSrc = "'self' 'unsafe-hashes'"

[build]
  command = "gridsome build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "10"
