[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    connectSrc = "'self'"
    imgSrc = "'self' data:"
    scriptSrc = "'self'"
    styleSrc = "'self' 'unsafe-hashes'"

[build]
  command = "gridsome build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "10"
